### ISSUE TITLE
xss & dos

### ISSUE THREAD

**Issue by GREEB** [Dan-Mizu/Project-Virtual-Pond#58]
Helllo thanks for the pond its very chill, i thought i would look at xss attacks because i was bored and i just wanted to keep the pond save. Unfortunately i crashed the hole thing.

Not sure what happened in the backend but after running:

```javascript
fetch("https://raw.githubusercontent.com/xsuperbug/payloads/master/XSS").then(async(e)=>{
	const d = await e.text()
        d.split('\n').forEach((e)=>client.playerSendingMessage(e))
})
```

the server crashed i guess i hit it too fast, maybe you could implement a debounce when sending messages. Otherwise ppl could dos the pond easily.

Thanks for the work :)

**Comment by Dan-Mizu** [comment]
The crash was unrelated to XSS.

There's a hard limit within the client to only allow 80 characters in a message, and the server reflects that when checking a message. Any player sending messages over 80 characters is kicked.

However, the "kick player" function had a small issue (already fixed in production) which caused the server to crash.

All messages from the client to the server are sanitized, so barriers to XSS attacks were already implemented. I do appreciate the help!
